dreamwalker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint1
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint2
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint3
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint4
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint1
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint2
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint3
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: limb_joint4
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint1
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint2
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint3
    pid: {p: 10.0, i: 0.00, d: 0.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint4
    pid: {p: 10.0, i: 0.00, d: 0.0}
